### ISSUE TITLE
Shifting of card when viewed on iPhones

### ISSUE THREAD

**Issue by AkshDesai04** [Dharmik48/profile-card-component-frontendmentor#1]
The card seems to lean towards the left seen in the 375x812 screen resolution.
The issue is absent on iPads and hence might point to an issue with a tighter aspect ratio.
![Screenshot](https://user-images.githubusercontent.com/68443055/119099859-f831a180-ba34-11eb-8db5-ea4046825ee3.png)

**Comment by AkshDesai04** [comment]
the issue seems to be with chrome emmulating the site and not the code

Sorry for generating the issue.

-Regards,
Aksh

**Comment by Dharmik48** [comment]
Okay, though thanks for informing
